baseurl = "https://taceywong.github.io/"
title = "Tacey"
theme = "vec"
languageCode = "en-us"
paginate = 20
disqusShortname = ""
googleAnalytics = ""

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post:博文"
    weight = 3
    url = "/post"
  [[menu.main]]
    name = "tags:标签"
    weight = 2
    url = "/tags"
  [[menu.main]]
    name = "categories:分类"
    weight = 1
    url = "/categories"
  [[menu.main]]
    name = "resume:简历"
    weight = 0
    url = "/resume"

[params]
  Keywords = "Tacey Wong,Seeking,Chasing,IT,Programing,Coding"
  Description = "Tacey's Blog:Seeking/求索/Chasing"
  Avatar = "img/avatar.png"
  SelfIntro = "Seeking/求索/Chasing"
  Email = "xinyong.wang@qq.com"

  GithubID = "TaceyWong"
  TwitterID = "tacey_w"
  FacebookID = "Tacey-Wong"
  LinkedInID = "tacey-wong-82b53487"
  GoogleplusID = "+王新勇"
  Weibo = "iTacey"
  QQ = "N/A"
  WeChat = "N/A"
